package com.sun.demo.mybatis.mapper;


import com.sun.demo.mybatis.entity.Org;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface OrgMapper {

    List<Org> queryOrg();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbg.generated
     */
    int insert(Org record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbg.generated
     */
    Org selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbg.generated
     */
    List<Org> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Org record);

    List<Org> querySubOrg(int id);
}